---
title: "Dataprep LISS SRV"
author: "Thijmen Jeroense"
bibliography: references.bib
date: "Last compiled on `r format(Sys.time(), '%B, %Y')`"
output: 
  html_document:
    toc:  true
    toc_float: true
    number_sections: false
    code_folding: show
    code_download: yes
---

```{r setup,globalsettings, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, cache=TRUE, results="hold", eval=FALSE, class.source=c("test"))
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"), results="hold", eval=FALSE)
options(width = 100)

colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}

```


```{r klippy, echo=FALSE, include=TRUE, eval=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```



```{css, echo=FALSE, eval=TRUE}

.watch-out {
  background-color: lightpink;
  border: 3px solid red;
  font-weight: bold;
}


pre.test {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 0px;
}

pre.test2 {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 0px;
  background-color: white
}


h1, .h1, h2, .h2, h3, .h3 {
    margin-top: 24px;
}


```

```{r packages, class.source="watch-out"}
#load packages.
library(dplyr)
library(haven)
library(purrr)
library(tidyr)
```




## Constructing the merged LISS data

```{r, eval=FALSE}
##---------------------------- LISS Merging ----------------------------##
#Dyad data preperation.
#Author: Thijmen Jeroense

#disable the scientific notation in R (else all the id's will be in scientific notation)
options(scipen = 999) #JT op het eind van dit script weer aan zetten? 

getwd()
setwd("C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/")


rm(list = ls())
##---------------------------- Data import and Merging the different LISS files ----------------------------##


#---------------------------------- LISS leisure and integration file ----------------------------------#

#import the different liss files from their directory. 
#file_names=as.list(dir(path="docs/data-raw/leisure_integ_data/", pattern = '*.sav')) #TJ I added DOCS/ as the data-raw exists in the docs dir. 
#create an empty list so that we can load all the files in this list. 
#desired_length <- 11 #
#liss_files <- vector(mode = "list", length = desired_length)

#import all the files in the list.
#for (i in 1:length(file_names)) {
#  liss_files[[i]] <- read_sav(paste("docs/data-raw/leisure_integ_data/",file_names[[i]], sep=""))
#}

#For a full outer join.
#liss_merged <- liss_files %>%
#  reduce(full_join, by = 'nomem_encr') %>% ##JT weird programming. ANSWER TJ: this is a common solution for this kind of problem: https://stackoverflow.com/questions/8091303/simultaneously-merge-multiple-data-frames-in-a-list 
#arrange the df on nomem_encr.
# arrange(nomem_encr)

#we now have a df based on 14473 observations and 4909 variables. 

#---------------------------------- Politics and Values ----------------------------------#

#do the same for the politics and values data. 
#get the politics and values data.
#I do this seperately as I wanted to create wave id's, and this was easier to do on one file.
#import the data files.
file_names=as.list(dir(path="C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/original_data/pol_data/", pattern = '*.sav'))
liss_files <- list()

#loop to load all the data in one list.
#name them. 
for (i in 1:length(file_names)) {
  liss_files[[i]] <- read_sav(paste("C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/original_data/pol_data/",file_names[[i]], sep=""))
} 

#merge the data into one file.
liss_pol <- liss_files %>%
  reduce(full_join, by = 'nomem_encr') %>%
  #order on nomem_encr
  arrange(nomem_encr)

#df with 14040 observations of 1978 variables. 

#remove the household id variables from the liss_pol and liss_merged file.
# they are incomplete as in some waves they are not present. I will add them later with the background data. 
liss_pol[,c("nohouse_encr", "nohouse_encr.x", "nohouse_encr.y", "nohouse_encr.x.x", "nohouse_encr.y.y")] <- NULL
#liss_merged[,c("nohouse_encr", "nohouse_encr.x", "nohouse_encr.y", "nohouse_encr.x.x", "nohouse_encr.y.y")] <- NULL

#---------------------------------- LISS CDN alter ids ----------------------------------#

#get the alter id handles.
# JT perhaps add some explanation how we retrieved this data. preferably in README.md. #Answer Thijmen: Will do. 

#import the data files.
#file_names=as.list(dir(path="C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/original_data/alter_data/", pattern = '*.sav'))
#liss_names_alters <- vector(mode = "list", length = 11)

#loop to load all the data in one list.
#name them. 
#for (i in 1:length(file_names)) {
#  liss_names_alters[[i]] <- read_sav(paste("C:/Users/u399171/surfdrive/Research/PhD project/data/LISS #data/original_data/alter_data/",file_names[[i]], sep=""))
#} 

#just to be sure, order the files on nomem_encr and add suffixes to the data.
#Then we can correctly identify the different waves. 
#liss_files <- lapply(1:11, function(i) {
#  data <- liss_names_alters[[i]]
  #Now I add suffixes to all the variables except the ID var, so we can correctly Identify the wave to which a variable belongs in the merged data. Otherwise we will have 11 sets of the same variables with a random .x or .y. 
#  names(data)[-1] <- paste0(names(data)[-1], sep = ".", c(1:11)[i])
#  return(data)
#})

#merge the data
#liss_alter <- liss_files %>%
#  reduce(full_join, by = 'nomem_encr') %>%
#  arrange(nomem_encr)

#---------------------------------- LISS background----------------------------------#
#import the background variable data. 
#import data files.
file_names=as.list(dir(path="C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/original_data/avars/", pattern = '*.sav'))
liss_files <- list()

#import the files in a for loop.
for (i in 1:length(file_names)) {
  liss_files[[i]] <- read_sav(paste("C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/original_data/avars/",file_names[[i]], sep=""))
} 

#just to be sure, order the files on nomem_encr and add suffixes to the data 
# JT Please explain the suffixes here and in text
liss_files <- lapply(1:12, function(i) {
  data <- liss_files[[i]][base::order(liss_files[[i]]$nomem_encr),]
  names(data)[-1] <- paste0(names(data)[-1], sep = ".", c(1:12)[i])
  return(data)
})

#merge the data. 
liss_background <- liss_files %>%
  reduce(full_join, by = 'nomem_encr') %>%
  arrange(nomem_encr)

#we now have a DF with 25281 observations of 341 variables. 

#----------------------------------Merging all the files into one wide file ----------------------------------#

#merge all the data with an full outer join into one file. 
#okay, let's merge the liss_merged, liss_alter and the politics and values waves.
liss <- liss_pol %>%
 # full_join(liss_alter, by = "nomem_encr") %>%
 # full_join(liss_pol, by = "nomem_encr") %>%
  full_join(liss_background, by = "nomem_encr") %>%
  arrange(nomem_encr)

#The final DF consists of 25306 observations with 7271 variables. 

#JT I think my strategy would be to use full joins and then afterwards use filters to select respondents. That way we know how many respondents we loose. We would like to report this in our manuscript right? 

#TJ: agree, I mow edited the procedure to use tidy as much as possible, some custom functions I prefer to use a loop for. For another version I will try to change this to tidy notation, but for now that will take up too much time. 

#clean the global environment.
#rm(file_names, liss_files, #liss_merged, liss_merged_alter, liss_names_alters, 
# desired_length, i, liss_pol, liss_background)
rm(list=ls()[! ls() %in% c("liss")])

#we now have 25306 cases of 7271 variables.

#--------------------------------------------- Filter out cases ------------------------------------------#
#we can use the month of datacollection to see whether someone has participated in a specific year/module combination
# if someone has an an NA they did not participate in it.
# so we want people who participated in the CDN module and also in the politics and values waves. 
# Let's create a filter of people who participated in at least one of thse. 
#example of wave 1 var. 
#table(liss$cs08a_m, useNA = 'always')

#first create a leisure and integration NA variable.
#first create a subset of the data, so we can use rowwise to create a selection id. 
#subset1 <- liss %>%
#  rowwise() %>%
  #create filter variable
#  mutate(na_lei_int = sum(is.na(c(cs08a_m, cs09b_m, cs10c_m, cs11d_m, cs12e_m, cs13f_m, cs14g_m, cs15h_m, cs16i_m, cs17j_m, cs18k_m)))) %>%
  #use only the observations that have participated in at least one wave of the leisure and integration data. We can of course change this later on. 
#  filter(na_lei_int < 11) %>%
#  ungroup()

#we go from 25306 cases to 14473 cases. 


#second create a pol val NA variable.
#filter out respondents who did not participate in any of the 11 waves. 
liss_subset <- liss %>%
  rowwise() %>%
  mutate(na_pol_val = sum(is.na(c(cv08a_m, cv09b_m, cv10c_m, cv11d_m, cv12e_m, cv13f_m, cv14g_m,
         cv17i_m, cv18j_m1, cv18j_m2, cv18j_m3, cv19k_m1, cv19k_m2, cv19k_m3,cv20l_m1, cv20l_m2, cv20l_m3)))) %>%
  filter(na_pol_val < 17) %>% #now it is 14, due the weird coding in 18/19. 
  ungroup()
  
#we go from 14473 cases to 13273 cases. We will work with this liss_subset dataframe. 

#--------------------------------------------- Variable selection from the complete liss file --------------------------------------------#
# JT: could you please make a folder with all codebooks so I/reviewers can look up the variable names. 
# Check

#create subset of all the data that I want for every wave. Then we can make a new file where we only have the selected data that we want.
#liss politics variables that I need
liss_pol <- liss_subset %>%
  select(nomem_encr, cv08a012,cv08a047, cv08a048, cv08a049, cv08a050, cv08a051, cv08a052, cv08a058, cv08a101, cv08a102, cv08a103, cv08a104, cv08a105, cv08a001, cv08a044, cv08a014, cv08a106, cv08a107, cv08a108, cv08a109,cv08a110,cv08a111,cv08a112,cv08a113,cv08a114,cv08a115, cv08a116,cv08a117,cv08a118,cv08a119,cv08a120,cv08a121,cv08a122,cv08a123,
         cv09b012,cv09b047, cv09b048, cv09b049, cv09b050, cv09b051, cv09b052, cv09b058, cv09b101, cv09b102, cv09b103, cv09b104, cv09b105, cv09b001, cv09b044, cv09b014,cv09b106, cv09b107, cv09b108, cv09b109,cv09b110,cv09b111,cv09b112,cv09b113,cv09b114,cv09b115,cv09b116,cv09b117,cv09b118,cv09b119,cv09b120,cv09b121,cv09b122,cv09b123,
         cv10c012,cv10c047, cv10c048, cv10c049, cv10c050, cv10c051, cv10c052, cv10c058, cv10c101, cv10c102, cv10c103, cv10c104, cv10c105, cv10c001, cv10c044, cv10c014,cv10c106, cv10c107, cv10c108, cv10c109,cv10c110,cv10c111,cv10c112,cv10c113,cv10c114,cv10c115,cv10c116,cv10c117,cv10c118,cv10c119,cv10c120,cv10c121,cv10c122,cv10c123,
         cv11d012,cv11d047, cv11d048, cv11d049, cv11d050, cv11d051, cv11d052, cv11d171, cv11d101, cv11d102, cv11d103, cv11d104, cv11d105, cv11d001, cv11d044, cv11d014,cv11d106, cv11d107, cv11d108, cv11d109,cv11d110,cv11d111,cv11d112,cv11d113,cv11d114,cv11d115, cv11d116,cv11d117,cv11d118,cv11d119,cv11d120,cv11d121,cv11d122,cv11d123,
         cv12e012,cv12e047, cv12e048, cv12e049, cv12e050, cv12e051, cv12e052, cv12e171, cv12e101, cv12e102, cv12e103, cv12e104, cv12e105, cv12e001, cv12e044, cv12e014,cv12e106, cv12e107, cv12e108, cv12e109,cv12e110,cv12e111,cv12e112,cv12e113,cv12e114,cv12e115, cv12e116,cv12e117,cv12e118,cv12e119,cv12e120,cv12e121,cv12e122,cv12e123,
         cv13f012,cv13f047, cv13f048, cv13f049, cv13f050, cv13f051, cv13f052, cv13f209, cv13f101, cv13f102, cv13f103, cv13f104, cv13f105, cv13f001, cv13f044, cv13f014,cv13f106, cv13f107, cv13f108, cv13f109,cv13f110,cv13f111,cv13f112,cv13f113,cv13f114,cv13f115, cv13f116,cv13f117,cv13f118,cv13f119,cv13f120,cv13f121,cv13f122,cv13f123,
         cv14g012,cv14g047, cv14g048, cv14g049, cv14g050, cv14g051, cv14g052, cv14g209, cv14g101, cv14g102, cv14g103, cv14g104, cv14g105, cv14g001, cv14g044, cv14g014,cv14g106, cv14g107, cv14g108, cv14g109,cv14g110,cv14g111,cv14g112,cv14g113,cv14g114,cv14g115, cv14g116,cv14g117,cv14g118,cv14g119,cv14g120,cv14g121,cv14g122,cv14g123,
         cv16h012,cv16h047, cv16h048, cv16h049, cv16h050, cv16h051, cv16h052, cv16h209, cv16h101, cv16h102, cv16h103, cv16h104, cv16h105, cv16h001, cv16h044, cv16h014,cv16h106, cv16h107, cv16h108, cv16h109,cv16h110,cv16h111,cv16h112,cv16h113,cv16h114,cv16h115, cv16h116,cv16h117,cv16h118,cv16h119,cv16h120,cv16h121,cv16h122,cv16h123,
         cv17i012,cv17i047, cv17i048, cv17i049, cv17i050, cv17i051, cv17i052, cv17i244, cv17i101, cv17i102, cv17i103, cv17i104, cv17i105, cv17i001, cv17i044, cv17i014,cv17i106, cv17i107, cv17i108, cv17i109,cv17i110,cv17i111,cv17i112,cv17i113,cv17i114,cv17i115, cv17i116,cv17i117,cv17i118,cv17i119,cv17i120,cv17i121,cv17i122,cv17i123,
         cv18j012,cv18j047, cv18j048, cv18j049, cv18j050, cv18j051, cv18j052, cv18j243, cv18j101, cv18j102, cv18j103, cv18j104, cv18j105, cv18j001, cv18j044, cv18j014,cv18j106, cv18j107, cv18j108, cv18j109,cv18j110,cv18j111,cv18j112,cv18j113,cv18j114,cv18j115, cv18j116,cv18j117,cv18j118,cv18j119,cv18j120,cv18j121,cv18j122,cv18j123,
         cv19k012,cv19k047, cv19k048, cv19k049, cv19k050, cv19k051, cv19k052, cv19k243, cv19k101, cv19k102, cv19k103, cv19k104, cv19k105, cv19k001, cv19k044, cv19k014,cv19k106, cv19k107, cv19k108, cv19k109,cv19k110,cv19k111,cv19k112,cv19k113,cv19k114,cv19k115, cv19k116,cv19k117,cv19k118,cv19k119,cv19k120,cv19k121,cv19k122,cv19k123,
         cv20l012,cv20l047, cv20l048, cv20l049, cv20l050, cv20l051, cv20l052, cv20l243, cv20l101, cv20l102, cv20l103, cv20l104, cv20l105, cv20l001, cv20l044, cv20l014,cv20l106, cv20l107, cv20l108, cv20l109,cv20l110,cv20l111,cv20l112,cv20l113,cv20l114,cv20l115, cv20l116,cv20l117,cv20l118,cv20l119,cv20l120,cv20l121,cv20l122,cv20l123)


#change names.
names(liss_pol)<- c("nomem_encr", "pol_int.1"	,	"parl_donot_care.1"	,	"pol_part_int.1"	,	"no_influece.1"	,	"cap_act_pol.1"	,	"clear_picture.1"	,	"pol_compl.1"	,	"vote_int.1"	,	"lr_scale.1"	,	"euthanasia.1"	,	"income_diff.1"	,	"immigrants.1",	"eu_integration.1"	,"gov_sat.1", "satdem.1", "poltrust.1", "postmatfirst.1", "postmatsecond.1", "postmatthird.1", "workingmother.1", "childjobmother.1", "fulltimemother.1", "equalcontribution.1", "fatherworks.1", "fatherhousehold.1", "fatherschildcare.1", "differentculture.1", "foreignerculture.1", "asylum.1", "foreignsocsec.1", "toomanyforeigners.1", "foreignnotaccepted.1", "foreigneconomy.1", "neighborhood.1", 
                    "pol_int.2"	,	"parl_donot_care.2"	,	"pol_part_int.2"	,	"no_influece.2"	,	"cap_act_pol.2"	,	"clear_picture.2"	,	"pol_compl.2"	,	"vote_int.2"	,	"lr_scale.2"	,	"euthanasia.2"	,	"income_diff.2"	,	"immigrants.2"	,	"eu_integration.2"	,"gov_sat.2", "satdem.2", "poltrust.2","postmatfirst.2", "postmatsecond.2", "postmatthird.2", "workingmother.2", "childjobmother.2", "fulltimemother.2", "equalcontribution.2", "fatherworks.2", "fatherhousehold.2", "fatherschildcare.2", "differentculture.2", "foreignerculture.2", "asylum.2", "foreignsocsec.2", "toomanyforeigners.2", "foreignnotaccepted.2", "foreigneconomy.2", "neighborhood.2",
                    "pol_int.3"	,	"parl_donot_care.3"	,	"pol_part_int.3"	,	"no_influece.3"	,	"cap_act_pol.3"	,	"clear_picture.3"	,	"pol_compl.3"	,	"vote_int.3"	,	"lr_scale.3"	,	"euthanasia.3"	,	"income_diff.3"	,	"immigrants.3"	,	"eu_integration.3"	,"gov_sat.3", "satdem.3", "poltrust.3","postmatfirst.3", "postmatsecond.3", "postmatthird.3", "workingmother.3", "childjobmother.3", "fulltimemother.3", "equalcontribution.3", "fatherworks.3", "fatherhousehold.3", "fatherschildcare.3", "differentculture.3", "foreignerculture.3", "asylum.3", "foreignsocsec.3", "toomanyforeigners.3", "foreignnotaccepted.3", "foreigneconomy.3", "neighborhood.3",
                    "pol_int.4"	,	"parl_donot_care.4"	,	"pol_part_int.4"	,	"no_influece.4"	,	"cap_act_pol.4"	,	"clear_picture.4"	,	"pol_compl.4"	,	"vote_int.4"	,	"lr_scale.4"	,	"euthanasia.4"	,	"income_diff.4"	,	"immigrants.4"	,	"eu_integration.4"	,"gov_sat.4", "satdem.4", "poltrust.4","postmatfirst.4", "postmatsecond.4", "postmatthird.4", "workingmother.4", "childjobmother.4", "fulltimemother.4", "equalcontribution.4", "fatherworks.4", "fatherhousehold.4", "fatherschildcare.4","differentculture.4", "foreignerculture.4", "asylum.4", "foreignsocsec.4", "toomanyforeigners.4", "foreignnotaccepted.4", "foreigneconomy.4", "neighborhood.4",
                    "pol_int.5"	,	"parl_donot_care.5"	,	"pol_part_int.5"	,	"no_influece.5"	,	"cap_act_pol.5"	,	"clear_picture.5"	,	"pol_compl.5"	,	"vote_int.5"	,	"lr_scale.5"	,	"euthanasia.5"	,	"income_diff.5"	,	"immigrants.5"	,	"eu_integration.5"	,"gov_sat.5", "satdem.5", "poltrust.5","postmatfirst.5", "postmatsecond.5", "postmatthird.5", "workingmother.5", "childjobmother.5", "fulltimemother.5", "equalcontribution.5", "fatherworks.5", "fatherhousehold.5", "fatherschildcare.5","differentculture.5", "foreignerculture.5", "asylum.5", "foreignsocsec.5", "toomanyforeigners.5", "foreignnotaccepted.5", "foreigneconomy.5", "neighborhood.5",
                    "pol_int.6"	,	"parl_donot_care.6"	,	"pol_part_int.6"	,	"no_influece.6"	,	"cap_act_pol.6"	,	"clear_picture.6"	,	"pol_compl.6"	,	"vote_int.6"	,	"lr_scale.6"	,	"euthanasia.6"	,	"income_diff.6"	,	"immigrants.6"	,	"eu_integration.6"	,"gov_sat.6", "satdem.6", "poltrust.6","postmatfirst.6", "postmatsecond.6", "postmatthird.6", "workingmother.6", "childjobmother.6", "fulltimemother.6", "equalcontribution.6", "fatherworks.6", "fatherhousehold.6", "fatherschildcare.6","differentculture.6", "foreignerculture.6", "asylum.6", "foreignsocsec.6", "toomanyforeigners.6", "foreignnotaccepted.6", "foreigneconomy.6", "neighborhood.6",
                    "pol_int.7"	,	"parl_donot_care.7"	,	"pol_part_int.7"	,	"no_influece.7"	,	"cap_act_pol.7"	,	"clear_picture.7"	,	"pol_compl.7"	,	"vote_int.7"	,	"lr_scale.7"	,	"euthanasia.7"	,	"income_diff.7"	,	"immigrants.7"	,	"eu_integration.7"	,"gov_sat.7", "satdem.7", "poltrust.7","postmatfirst.7", "postmatsecond.7", "postmatthird.7", "workingmother.7", "childjobmother.7", "fulltimemother.7", "equalcontribution.7", "fatherworks.7", "fatherhousehold.7", "fatherschildcare.7","differentculture.7", "foreignerculture.7", "asylum.7", "foreignsocsec.7", "toomanyforeigners.7", "foreignnotaccepted.7", "foreigneconomy.7", "neighborhood.7",
                    "pol_int.8"	,	"parl_donot_care.8"	,	"pol_part_int.8"	,	"no_influece.8"	,	"cap_act_pol.8"	,	"clear_picture.8"	,	"pol_compl.8"	,	"vote_int.8"	,	"lr_scale.8"	,	"euthanasia.8"	,	"income_diff.8"	,	"immigrants.8"	,	"eu_integration.8"	,"gov_sat.8", "satdem.8", "poltrust.8","postmatfirst.8", "postmatsecond.8", "postmatthird.8", "workingmother.8", "childjobmother.8", "fulltimemother.8", "equalcontribution.8", "fatherworks.8", "fatherhousehold.8", "fatherschildcare.8","differentculture.8", "foreignerculture.8", "asylum.8", "foreignsocsec.8", "toomanyforeigners.8", "foreignnotaccepted.8", "foreigneconomy.8", "neighborhood.8",
                    "pol_int.9"	,	"parl_donot_care.9"	,	"pol_part_int.9"	,	"no_influece.9"	,	"cap_act_pol.9"	,	"clear_picture.9"	,	"pol_compl.9"	,	"vote_int.9"	,	"lr_scale.9"	,	"euthanasia.9"	,	"income_diff.9"	,	"immigrants.9"	,	"eu_integration.9","gov_sat.9", "satdem.9", "poltrust.9","postmatfirst.9", "postmatsecond.9", "postmatthird.9", "workingmother.9", "childjobmother.9", "fulltimemother.9", "equalcontribution.9", "fatherworks.9", "fatherhousehold.9", "fatherschildcare.9","differentculture.9", "foreignerculture.9", "asylum.9", "foreignsocsec.9", "toomanyforeigners.9", "foreignnotaccepted.9", "foreigneconomy.9", "neighborhood.9",
                    "pol_int.10"	,	"parl_donot_care.10"	,	"pol_part_int.10"	,	"no_influece.10"	,	"cap_act_pol.10"	,	"clear_picture.10"	,	"pol_compl.10"	,	"vote_int.10"	,	"lr_scale.10"	,	"euthanasia.10"	,	"income_diff.10"	,	"immigrants.10"	,	"eu_integration.10","gov_sat.10", "satdem.10", "poltrust.10", "postmatfirst.10", "postmatsecond.10", "postmatthird.10", "workingmother.10", "childjobmother.10", "fulltimemother.10", "equalcontribution.10", "fatherworks.10", "fatherhousehold.10", "fatherschildcare.10","differentculture.10", "foreignerculture.10", "asylum.10", "foreignsocsec.10", "toomanyforeigners.10", "foreignnotaccepted.10", "foreigneconomy.10", "neighborhood.10",
                    "pol_int.11"	,	"parl_donot_care.11"	,	"pol_part_int.11"	,	"no_influece.11"	,	"cap_act_pol.11"	,	"clear_picture.11"	,	"pol_compl.11"	,	"vote_int.11"	,	"lr_scale.11"	,	"euthanasia.11"	,	"income_diff.11"	,	"immigrants.11"	,	"eu_integration.11","gov_sat.11", "satdem.11", "poltrust.11", "postmatfirst.11", "postmatsecond.11", "postmatthird.11", "workingmother.11", "childjobmother.11", "fulltimemother.11", "equalcontribution.11", "fatherworks.11", "fatherhousehold.11", "fatherschildcare.11","differentculture.11", "foreignerculture.11", "asylum.11", "foreignsocsec.11", "toomanyforeigners.11", "foreignnotaccepted.11", "foreigneconomy.11", "neighborhood.11", 
                    "pol_int.12"	,	"parl_donot_care.12"	,	"pol_part_int.12"	,	"no_influece.12"	,	"cap_act_pol.12"	,	"clear_picture.12"	,	"pol_compl.12"	,	"vote_int.12"	,	"lr_scale.12"	,	"euthanasia.12"	,	"income_diff.12"	,	"immigrants.12"	,	"eu_integration.12","gov_sat.12", "satdem.12", "poltrust.12", "postmatfirst.12", "postmatsecond.12", "postmatthird.12", "workingmother.12", "childjobmother.12", "fulltimemother.12", "equalcontribution.12", "fatherworks.12", "fatherhousehold.12", "fatherschildcare.12","differentculture.12", "foreignerculture.12", "asylum.12", "foreignsocsec.12", "toomanyforeigners.12", "foreignnotaccepted.12", "foreigneconomy.12", "neighborhood.12")	


#get the background data and rename the columns. 
liss_avars <- liss_subset %>%
  select(geslacht.1,positie.1,gebjaar.1,leeftijd.1,lftdcat.1,aantalhh.1,aantalki.1,partner.1,burgstat.1,woonvorm.1,woning.1,sted.1,belbezig.1,brutoink.1,nettoink.1,brutocat.1,nettocat.1,oplzon.1,oplmet.1,oplcat.1, nohouse_encr.1,
         geslacht.2,positie.2,gebjaar.2,leeftijd.2,lftdcat.2,aantalhh.2,aantalki.2,partner.2,burgstat.2,woonvorm.2,woning.2,sted.2,belbezig.2,brutoink.2,nettoink.2,brutocat.2,nettocat.2,oplzon.2,oplmet.2,oplcat.2, nohouse_encr.2,
         geslacht.3,positie.3,gebjaar.3,leeftijd.3,lftdcat.3,aantalhh.3,aantalki.3,partner.3,burgstat.3,woonvorm.3,woning.3,sted.3,belbezig.3,brutoink.3,nettoink.3,brutocat.3,nettocat.3,oplzon.3,oplmet.3,oplcat.3, nohouse_encr.3,
         geslacht.4,positie.4,gebjaar.4,leeftijd.4,lftdcat.4,aantalhh.4,aantalki.4,partner.4,burgstat.4,woonvorm.4,woning.4,sted.4,belbezig.4,brutoink.4,nettoink.4,brutocat.4,nettocat.4,oplzon.4,oplmet.4,oplcat.4, nohouse_encr.4,
         geslacht.5,positie.5,gebjaar.5,leeftijd.5,lftdcat.5,aantalhh.5,aantalki.5,partner.5,burgstat.5,woonvorm.5,woning.5,sted.5,belbezig.5,brutoink.5,nettoink.5,brutocat.5,nettocat.5,oplzon.5,oplmet.5,oplcat.5, nohouse_encr.5,
         geslacht.6,positie.6,gebjaar.6,leeftijd.6,lftdcat.6,aantalhh.6,aantalki.6,partner.6,burgstat.6,woonvorm.6,woning.6,sted.6,belbezig.6,brutoink.6,nettoink.6,brutocat.6,nettocat.6,oplzon.6,oplmet.6,oplcat.6, nohouse_encr.6,
         geslacht.7,positie.7,gebjaar.7,leeftijd.7,lftdcat.7,aantalhh.7,aantalki.7,partner.7,burgstat.7,woonvorm.7,woning.7,sted.7,belbezig.7,brutoink.7,nettoink.7,brutocat.7,nettocat.7,oplzon.7,oplmet.7,oplcat.7, nohouse_encr.7,
         geslacht.8,positie.8,gebjaar.8,leeftijd.8,lftdcat.8,aantalhh.8,aantalki.8,partner.8,burgstat.8,woonvorm.8,woning.8,sted.8,belbezig.8,brutoink.8,nettoink.8,brutocat.8,nettocat.8,oplzon.8,oplmet.8,oplcat.8, nohouse_encr.8,
         geslacht.9,positie.9,gebjaar.9,leeftijd.9,lftdcat.9,aantalhh.9,aantalki.9,partner.9,burgstat.9,woonvorm.9,woning.9,sted.9,belbezig.9,brutoink.9,nettoink.9,brutocat.9,nettocat.9,oplzon.9,oplmet.9,oplcat.9, nohouse_encr.9,
         geslacht.10,positie.10,gebjaar.10,leeftijd.10,lftdcat.10,aantalhh.10,aantalki.10,partner.10,burgstat.10,woonvorm.10,woning.10,sted.10,belbezig.10,brutoink.10,nettoink.10,brutocat.10,nettocat.10,oplzon.10,oplmet.10,oplcat.10, nohouse_encr.10,
         geslacht.11,positie.11,gebjaar.11,leeftijd.11,lftdcat.11,aantalhh.11,aantalki.11,partner.11,burgstat.11,woonvorm.11,woning.11,sted.11,belbezig.11,brutoink.11,nettoink.11,brutocat.11,nettocat.11,oplzon.11,oplmet.11,oplcat.11, nohouse_encr.11,
         geslacht.12,positie.12,gebjaar.12,leeftijd.12,lftdcat.12,aantalhh.12,aantalki.12,partner.12,burgstat.12,woonvorm.12,woning.12,sted.12,belbezig.12,brutoink.12,nettoink.12,brutocat.12,nettocat.12,oplzon.12,oplmet.12,oplcat.12, nohouse_encr.12)

#get the background data and rename the columns.
#For the first three waves there are is no data on this variable
liss_origin <- liss_subset %>%
  select(herkomstgroep.4, herkomstgroep.5, herkomstgroep.6, herkomstgroep.7, herkomstgroep.8, herkomstgroep.9, herkomstgroep.10, herkomstgroep.11, herkomstgroep.12)
names(liss_origin) <- c("origin.4", "origin.5", "origin.6", "origin.7", "origin.8", "origin.9", "origin.10","origin.11", "origin.12")

#create ego origin 1-3 with NA's so we can later merge them into a long file. 
liss_origin$origin.1 <- NA
liss_origin$origin.2 <- NA
liss_origin$origin.3 <- NA

#For some reason the reshape command bugs when the ordering is not correct. 
liss_origin <- liss_origin[,c(9:11,1:8)]

#combine the different data sources into one wide data file. 
liss_wide <- cbind(liss_pol, liss_avars, liss_origin)


#------------------------------------- Variable recode -----------------------------------------------#
#reverse code political discussion frequency and eu_integration.

#eu integration.
list <- liss_wide[,grep(names(liss_wide), pattern = "eu_integration", value = T)]
#reverse code in another list and compare the two: it works. 
list2 <- apply(list, 2, function(x)5 - x)
#replace original variables with the reverse coded variable. 
liss_wide[,grep(names(liss_wide), pattern = "eu_integration", value = T)] <- list2

#--------------------------- Reshape to long file. -------------------------#
#TJ: In the future I want to change this to a tidy function such as pivot_longer. For now I have not figured it out yet. (application of pivot_wide() was succesful).

#@JT, what do you use for reshaping wide to long and vice versa?
liss_srv_subset <- liss_wide  %>%
  select(nomem_encr, oplmet.1, oplmet.2, oplmet.3, oplmet.4, oplmet.5, oplmet.6, oplmet.7, oplmet.8, oplmet.9, oplmet.10, oplmet.11, oplmet.12,
         eu_integration.1, eu_integration.2, eu_integration.3, eu_integration.4, eu_integration.5, eu_integration.6, eu_integration.7, eu_integration.8, eu_integration.9, eu_integration.10, eu_integration.11, eu_integration.12,
         immigrants.1, immigrants.2, immigrants.3, immigrants.4, immigrants.5, immigrants.6, immigrants.7, immigrants.8, immigrants.9, immigrants.10, immigrants.11, immigrants.12,
         sted.1, sted.2, sted.3, sted.4, sted.5, sted.6, sted.7, sted.8, sted.9, sted.10, sted.11, sted.12)
         

#create a long file.
liss_srv_subset <- reshape(liss_srv_subset, direction = "long",
                     varying = names(liss_srv_subset[,2:49]),
                     idvar = "nomem_encr",
                     timevar = "survey_wave",
                     times = c(1:12))


#clean the environment. 
rm(list=ls()[! ls() %in% c("liss_srv_subset", "liss_wide")])


#Export the data #
#save RData.
save.image("C:/Users/u399171/surfdrive/Research/PhD project/data/LISS data/created_data/LISS_srv_blog_polar.Rdata")

```

